---
- name: Check if Nextcloud is currently installed
  ansible.builtin.lineinfile:
    path: "{{home_dir}}.local/share/containers/storage/volumes/nextcloud/conf.php"
    regex: ".+installed\\s*=>\\s*true"
    state: absent
  check_mode: yes
  register: installed
- name: Run installer commands if needed
  block:
    - name: Run Installer 
      containers.podman.podman_container:
        command: "occ maintenance:install --database \"mysql\" --database-name \"nextcloud\"  --database-user \"nextcloud\" --database-pass \"{{lookup('ansible.builtin.password', '/tmp/.mysql.pass', seed=inventory_hostname)}}\" --admin-user \"admin\" --admin-pass \"{{admin_password}}\""
        detach: no
        image: docker.io/nextcloud:{{nextcloud_version}}-fpm
        name: nextcloud-config
  when: installed is changed
