---
- name: Ensure generic required packages
  ansible.builtin.package:
    name: 
      - podman
      - acl
      - python3-cryptography
    state: latest
  vars:
    ansible_become: yes
- name: Ensure RHEL family specific packages
  ansible.builtin.package:
    name:
      - container-selinux
      - cronie
      - setools
  when: ansible_os_family == "RedHat"
- name: Ensure System Configuration
  include_tasks: tasks/system-configuration.yml
  vars:
    ansible_become: yes
- name: Ensure User Configuration
  include_tasks: tasks/user-configuration.yml
  vars:
    ansible_become: yes
    ansible_become_user: nextcloud
