---
- name: Ensure required packages
  ansible.builtin.package:
    name: 
      - podman
      - container-selinux
      - setools
      - acl
      - cronie
      - python3-cryptography
    state: latest
  vars:
    ansible_become: yes
- name: Ensure System Configuration
  include_tasks: tasks/system-configuration.yml
  vars:
    ansible_become: yes
- name: Ensure User Configuration
  include_tasks: tasks/user-configuration.yml
  vars:
    ansible_become: yes
    ansible_become_user: nextcloud
