- name: Ensure podman volumes
  containers.podman.podman_volume:
    name: nextcloud-{{item}}
    state: present
  with_items:
    - fpm
    - mysql
    - redis
    - nginx
- name: Ensure correct volume permissions 
  ansible.builtin.file:
    group: nextcloud
    mode: 0770
    owner: nextcloud
    path: "{{item}}"
    setype: container_file_t
    state: directory
  with_fileglob: "{{home_dir}}/.local/share/containers/storage/volumes/*"
- name: Ensure systemd services
  ansible.builtin.template:
    src: "{{item}}"
    dest: "{{home_dir}}/.config/systemd/user/{{item|basename|regex_replace('(^.*)\\.j2', '\\1')}}"
    owner: nextcloud
    group: nextcloud
    mode: 0660
  with_fileglob: "templates/*.service.j2"
  register: unit_install
- name: Ensure nginx configuration
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: "{{home_dir}}/.local/share/containers/storage/volumes/nextcloud-nginx/_data/nginx.conf"
    owner: nextcloud
    group: nextcloud
    mode: 0660
- name: Ensure private key exists in nginx volume
  community.crypto.openssl_privatekey:
    path: "{{home_dir}}/.local/share/containers/storage/volumes/nextcloud-nginx/_data/nextcloud.key"
    size: 4096
    mode: 0600
    type: RSA
- name: Ensure self signed certificate is present
  community.crypto.x509_certificate:
    path: "{{home_dir}}/.local/share/containers/storage/volumes/nextcloud-nginx/_data/nextcloud-ss.crt"
    privatekey_path: "{{home_dir}}/.local/share/containers/storage/volumes/nextcloud-nginx/_data/nextcloud.key"
    provider: selfsigned
    selfsigned_not_after: "+1095d"
    mode: 0644
- name: Reload systemd daemon
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
  when: unit_install is changed
- name: Ensure services are enabled and started
  ansible.builtin.systemd:
    enabled: true
    name: "{{item}}"
    scope: user
    state: started
  with_items:
    - nextcloud-fpm
    - nextcloud-mysql
    - nextcloud-nginx
    - nextcloud-redis
- name: Ensure cron job
  ansible.builtin.cron:
    name: Cron job for Nextcloud
    minute: "*/5"
    job: "podman exec -it nextcloud-fpm php -f /var/www/html/cron.php"
