---
- name: Converge
  hosts: all
  tasks:
    - name: "Include codyswanson4.nextcloud"
      include_role:
        name: "codyswanson4.nextcloud"
      vars:
        nextcloud_admin_password: "testpass123!"
        nextcloud_trusted_domains: localhost
        listen_ip: 127.0.0.1
