---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: fedora/37-cloud-base
  - name: instance
    box: ubuntu/jammy64
provisioner:
  name: ansible
verifier:
  name: ansible
